[package]
name = "bytecode-rs"
version = "0.1.0"
edition = "2021"
authors = ["NaokiM03"]
description = "This library provides the ability to read bytecode."
repository = "https://github.com/NaokiM03/bytecode-rs"
readme = "README.md"
license = "MIT"

[dependencies]
tiny-ansi = "0.1.0"
